theme: jekyll-theme-minimal
title: OpenVE
description: Es un intento de hacer algo verdaderamente Open Source para Venezuela
show_downloads: false
logo: openve.png
telegram: https://t.me/openve
repository: openve/comunidades-en-telegram
exclude:
- Gemfile
plugins:
  - jekyll-avatar
