theme: jekyll-theme-minimal
title: OpenVE
description: Es un intento de hacer algo verdaderamente Open Source para Venezuela
show_downloads: false
logo: openve.svg
telegram: https://t.me/openve
exclude:
- Gemfile
plugins:
  - jekyll-avatar
